### ISSUE TITLE
learn how to use .gitignore

### ISSUE THREAD

**Issue by vbezl** [whitebaronnb/MySQL#1]
remove all unnecessary files and folders from git - like venv, localhost, .idea etc.
use .gitignore for that purpose

**Comment by nickborovik** [comment]
fixed. all unnecessary files gone from this repository

**Comment by vbezl** [comment]
following sql files have also nothing to do with the project:
sys_routines.sql
sys_sys_config.sql

**Comment by nickborovik** [comment]
removed, thnx!

**Comment by vbezl** [comment]
good
