### ISSUE TITLE
programming naming conventions

### ISSUE THREAD

**Issue by vbezl** [whitebaronnb/MySQL#2]
there are few standard naming conventions and it's better to learn them from the beginning to have a nice style habit

google: 
programming naming conventions
sql naming conventions
python naming conventions

**Comment by nickborovik** [comment]
thnx, now i fixed my first names in DB
same for python code, renamed a few variables
soon will be new commit

**Comment by nickborovik** [comment]
MySQLDump/sys_guests.sql
MySQLDump/sys_phones.sql
uploaded new commit


 ```
`guest_Id` int NOT NULL AUTO_INCREMENT,
  `guest_FirstName` varchar(50) DEFAULT NULL,
  `guest_LastName` varchar(50) DEFAULT NULL,
  `guest_Email` varchar(100) DEFAULT NULL,

`guest_id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
```

**Comment by vbezl** [comment]
perfect
