### ISSUE TITLE
guest email is not unique - don't count on it to be unique if it's not

### ISSUE THREAD

**Issue by vbezl** [whitebaronnb/MySQL#3]
https://github.com/whitebaronnb/MySQL/blob/5997f81eb3b0721dfc5ee5da947660bc36636c4e/mysql_guest_phone.py#L26

there might be many records with the same email according to your db structure
use "mysql last insert id" to get the id of the record you have just inserted

**Comment by nickborovik** [comment]
https://github.com/whitebaronnb/MySQL/blob/a4c86854739106e257bc46a33d0bc2c525987de1/mysql_python.py#L25
fixed, thnx!

**Comment by vbezl** [comment]
you don't need to fetch it separately - just use it in the next query

**Comment by nickborovik** [comment]
https://github.com/whitebaronnb/MySQL/blob/0bcf432272e0d9185a45a2ede71fd999cbf1178f/mysql_python.py#L25-L33

Like that?

**Comment by vbezl** [comment]
almost (continue in #4 )
